### ISSUE TITLE
Support basic config/configuration.yml for "smtp_settings" .etc

### ISSUE THREAD

**Issue by sanak** [gtt-project/docker-gtt#17]
**Problem**
Official Redmine Docker (https://github.com/docker-library/redmine) seems not to support basic `config/configuration.yml`, so supporting this (like `smtp_settings`) may be better.

**Improvement**
To support this, I am thinking to add the following files:
- `.env.example`: To define environment variables template. (Need to copy it to `.env` for `docker-compose.yml` detect it.)
-  `config/configuration.yml`: Add this with above environment variables and mount (share) on host as `docker-compose.yml` volume configuration.

For future (like AWS ECS container work .etc), supporting @aruneko's following example configurations (like `puma`, `lograge` and `cors`) will become necessary, but at this moment, above basic cofniguration may be enough.
- https://github.com/aruneko/redmica/compare/stable-1.1..dockerize-1.1

**Alternatives**
I don't know other good alternatives.

**Comment by dkastl** [comment]
I don't see where `configuration.yml` is configured in https://github.com/aruneko/redmica/compare/stable-1.1..dockerize-1.1

But we could add a `config/configuration.yml` with environment variables, so it doesn't need to be mounted.

**Comment by sanak** [comment]
@dkastl Oh, yes. Adding `COPY` command in `Dockerfile`, volume mount will not be necessary, but I may take more time to build docker image several times (just possibility...).

**Comment by sanak** [comment]
Well, I supported this with `COPY` command way, so I will close this.
