### ISSUE TITLE
Add submodule "redmine_gtt_print`

### ISSUE THREAD

**Issue by dkastl** [gtt-project/docker-gtt#2]
The most important plugin is `redmine_gtt_print`.

Add this plugin as Git Submodule when the plugin is available on Github:

```
git submodule add -f https://github.com/gtt-project/redmine_gtt_print.git redmine/plugins/redmine_gtt_print
```

**Comment by sanak** [comment]
Well, I modified folder structure, so the command will be as follows:
```sh
```
git submodule add -f https://github.com/gtt-project/redmine_gtt_print.git plugins/redmine_gtt_print
```

**Comment by dkastl** [comment]
Right. The issues are a bit old and outdated.

**Comment by sanak** [comment]
I close this.
