### ISSUE TITLE
Build JS/CSS with webpack is necessary

### ISSUE THREAD

**Issue by dkastl** [gtt-project/docker-gtt#25]
With the refactoring done by @smellman it's necessary to also build the Javascript of `redmine_gtt` plugin with webpack before starting the service: https://github.com/gtt-project/redmine_gtt/tree/develop

```
cd redmine_gtt
yarn
npx webpack
```

**Comment by sanak** [comment]
Current image base `ruby:2.6-slim-buster` installable node version seems to be quite old (v10.24.0),  
- https://packages.debian.org/ja/buster/nodejs

so I will try to install Node.js v14 (LTS) manually on the Dockerfile.
- https://computingforgeeks.com/install-node-js-14-on-ubuntu-debian-linux/

**Comment by sanak** [comment]
@dkastl Well, I will try to exclude `plugins/redmine_gtt/assets/javascripts` with original `feature/npx-webpack-build` way...
