### ISSUE TITLE
Upgrade redmine version from 4.2.0 to 4.2.3 (with upgrading pg version default from 1.1.4 to 1.2.2)

### ISSUE THREAD

**Issue by sanak** [gtt-project/docker-gtt#36]
**Improvement**
This is not so urgent, but checking latest redmine released version may be better.

**Comment by dkastl** [comment]
Great, we already can skip one release: https://www.redmine.org/news/132

**Comment by dkastl** [comment]
Version 4.2.3 has been released https://redmine.org/projects/redmine/wiki/Download

**Comment by sanak** [comment]
Already done with #50. Close this.
