### ISSUE TITLE
Add Mapfish Print Docker image to the setup

### ISSUE THREAD

**Issue by dkastl** [gtt-project/docker-gtt#7]
To be able to use the GTT Print extension (see #2 ) Mapfish Print needs to be available:

- [x] Add service to Docker Commpose
- [x] Enable Japanese fonts
- [x] Sample print template

Some more resources about adding Japanese fonts:
- https://community.jaspersoft.com/wiki/biao-zhun-yi-wai-nohuontowojaspersoft-studiodeshi-itai
- https://qiita.com/AkihiroTakamura/items/da7f7ef2d7da21a17ef1

Official Mapfish Docker images:
- https://mapfish.github.io/mapfish-print-doc/docker.html
- https://hub.docker.com/r/camptocamp/mapfish_print/

**Comment by sanak** [comment]
I close this, once.
